import os
import pickle


def load_latent_variables(infile):
    """Load latent variables from cryoDRGN z.pkl file.

    Parameters
    ----------
    infile : string
        z.pkl file generated by cryoDRGN.

    Returns
    -------
    ndarray
        Array containing the latent variables. shape=(num_samples, num_variables)
    """

    assert os.path.exists(infile)
    with open(infile, 'rb') as f:
        Z = pickle.load(f)
    return Z
